module.exports = {
  userDB: require("./userModel"),
  permitDB: require("./permitModel"),
  roleDB: require("./roleModel"),
  categoryDB: require("./categoryModel"),
  subCategoryDB: require("./subCategoryModel"),
  childCategoryDB: require("./childCategoryModel"),
  deliveryDB: require("./DeliverModels"),
  warrantyDB: require("./warrantyModel"),
  orderDB: require("./OrderModel"),
  orderItemDB: require("./OrderItemModel"),
  productDB: require("./ProductModel"),
  messageDB: require("./messageModel"),
  unreadDB: require("./unreadModel"),
};
